### ISSUE TITLE
DNS pod stuck in ContainerCreating

### ISSUE THREAD

**Issue by InfantSwain** [projectcalico/app-policy#1]
I tried to follow the steps mentioned to recreate the app-policy demo. After the VM's come up, once I issue the command (kubectl apply -f config/install/05-calico.yaml) to bringup the calico pods, I see that the DNS pod is stuck. Here are the details

#kubectl get pods --all-namespaces -o wide
NAMESPACE     NAME                 READY     STATUS              RESTARTS   AGE       IP              NODE
kube-system   calico-node-27nbg    2/2       Running             0          50m       172.18.18.101   172.18.18.101
kube-system   calico-node-kh8mn    2/2       Running             0          50m       172.18.18.103   172.18.18.103
kube-system   calico-node-nqkt4    2/2       Running             0          50m       172.18.18.102   172.18.18.102
kube-system   kube-dns-v19-mmwdg   0/3       ContainerCreating   0          9m        <none>          172.18.18.102

#kubectl get nodes
NAME            STATUS                     ROLES     AGE       VERSION
172.18.18.101   Ready,SchedulingDisabled   <none>    1h        v1.8.4
172.18.18.102   Ready                      <none>    1h        v1.8.4
172.18.18.103   Ready                      <none>    1h        v1.8.4
 
####Here is the o/p of describe pods error information
Events:
  Type     Reason                  Age               From                    Message
  ----     ------                  ----              ----                    -------
  Warning  FailedScheduling        1m (x6 over 1m)   default-scheduler       No nodes are available that match all of the predicates: NodeNotReady (2), NodeUnschedulable (1).
  Normal   Scheduled               1m                default-scheduler       Successfully assigned kube-dns-v19-cnkkc to 172.18.18.102
  Normal   SuccessfulMountVolume   1m                kubelet, 172.18.18.102  MountVolume.SetUp succeeded for volume "kube-dns-token-xxbtg"
  Warning  FailedCreatePodSandBox  59s (x8 over 1m)  kubelet, 172.18.18.102  Failed create pod sandbox.
  Warning  FailedSync              59s (x8 over 1m)  kubelet, 172.18.18.102  Error syncing pod
  Normal   SandboxChanged          59s (x8 over 1m)  kubelet, 172.18.18.102  Pod sandbox changed, it will be killed and re-created.

**Comment by spikecurtis** [comment]
Is this an intermittent issue, or does it happen every time you try to bring up the cluster?

The pod error information is coming from Kubelet, so it might be helpful to look at the kubelet logs as well.

**Comment by InfantSwain** [comment]
This happens all the time. I'm guessing something basic is broken. I have tried it more than 5 times in last 3 days and it happened every time. I kind of looked at kubelet logs and as well tried to change the portmap based on suggestions on other forums with no luck.

**Comment by spikecurtis** [comment]
I was able to repro this. Sorry for the delay; I believe the issue was due to incompatible versions between the CNI plug in and `calico-node` (the former was using the `latest` tag, but the latter was pinned).  I have updated the demo manifest to pin both versions: https://github.com/projectcalico/app-policy/commit/c5a5fd62df20c0eb2b897bc975ea0099ecf53487

@InfantSwain give it a go and if it works for you, please close this issue.

**Comment by InfantSwain** [comment]
Tested works now.
